#!/usr/bin/env bash

PROJECTPATH="projects/${1}"
DISTPATH="dist/${1}"

# bump the version
cd $PROJECTPATH
VERSION="$(npm version patch)"
cd ../..

echo "Publishing ${1} version ${VERSION}..."

# build the lib
ng build $1 --prod

# publish to NPM
cd $DISTPATH
npm publish --access public
cd ../..



# commit
git add -A
git commit -m "published ${1} version ${VERSION} to npm"
